kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres
  namespace: dev
  labels:
    app: postgres
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi