steps:
  #This step will copy core jar to gcs location.
  - name: 'asia.gcr.io/$PROJECT_ID/scala-sbt'
    args: ['project core', 'clean', 'assembly', 'project root', 'publishLocal', 'project examples', 'package']

  - name: 'asia.gcr.io/$PROJECT_ID/scala-sbt'
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        set -x && \
        sbt 'inspect actual version' | grep "Setting: java.lang.String" | cut -d '=' -f2 | tr -d ' ' > /workspace/version.txt

  #This step will copy core jar to gcs location.
  - name: 'gcr.io/cloud-builders/gsutil'
    id: Copy core jar
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        set -x && \
        gsutil cp /workspace/modules/core/target/scala-2.12/etlflow-core-assembly-$(cat /workspace/version.txt).jar ${_GCS_BUCKET}

  #This step will copy examples jar to gcs location.
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp','/workspace/examples/target/scala-2.12/etlflow-examples_2.12-$(cat /workspace/version.txt).jar','${_GCS_BUCKET}']