name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_PASSWORD: etlflow
          POSTGRES_USER: etlflow
          POSTGRES_DB: etlflow
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      run: sbt ";project root; publishLocal; project examples; runMain examples.LoadData run_db_migration; project core; test;"
      env:
        LOG_DB_URL: jdbc:postgresql://postgres:5432/etlflow
        LOG_DB_USER: etlflow
        LOG_DB_PWD: etlflow
        LOG_DB_DRIVER: org.postgresql.Driver
